name: Build and Publish

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]
    types: [ opened, synchronize, reopened, closed ]
  workflow_dispatch:

permissions:
  contents: write
  pull-requests: write

jobs:
  build:
    uses: ./.github/workflows/build-vscode-extension.yml
    secrets:
      VSCE_PAT: ${{ secrets.VSCE_PAT }}
